// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {audio} from '../models';
import {identity} from '../models';
import {resilience} from '../models';
import {input} from '../models';
import {logutil} from '../models';
import {app} from '../models';
import {tailscale} from '../models';

export function AddPeer(arg1:string):Promise<void>;

export function ClearReturnAnchor():Promise<void>;

export function ClearTriggerZone():Promise<void>;

export function Connect(arg1:string):Promise<void>;

export function DiscardReceivedFiles(arg1:string):Promise<void>;

export function Disconnect():Promise<void>;

export function GetAudioDevices():Promise<Array<audio.AudioDevice>>;

export function GetAudioMode():Promise<string>;

export function GetAudioProfile():Promise<string>;

export function GetAudioTiming():Promise<string>;

export function GetAudioTransport():Promise<string>;

export function GetAutoReconnect():Promise<boolean>;

export function GetAutostart():Promise<boolean>;

export function GetCaptureDeviceID():Promise<string>;

export function GetDevice():Promise<identity.DeviceInfo>;

export function GetEdgeSide():Promise<string>;

export function GetExitHotkey():Promise<Record<string, number>>;

export function GetHealthStatus():Promise<resilience.HealthStatus>;

export function GetLastPeer():Promise<Record<string, string>>;

export function GetLoadMetrics():Promise<Record<string, number>>;

export function GetLocalMonitors():Promise<Array<input.MonitorInfo>>;

export function GetLogAnalysis():Promise<logutil.LogAnalysis>;

export function GetMicDeviceID():Promise<string>;

export function GetMicMode():Promise<string>;

export function GetMicPlaybackDeviceID():Promise<string>;

export function GetMuteSource():Promise<boolean>;

export function GetPeers():Promise<Array<app.PeerInfo>>;

export function GetPlaybackDeviceID():Promise<string>;

export function GetRecentLogs():Promise<Array<string>>;

export function GetReturnAnchor():Promise<Record<string, any>>;

export function GetSensitivity():Promise<number>;

export function GetSession():Promise<app.SessionStatus>;

export function GetStartMinimized():Promise<boolean>;

export function GetTailscaleStatus():Promise<tailscale.Status>;

export function GetTriggerZone():Promise<Record<string, any>>;

export function PickAndSendFiles():Promise<void>;

export function Reconnect():Promise<void>;

export function RemovePeer(arg1:string):Promise<void>;

export function SaveReceivedFiles(arg1:string):Promise<app.SaveReceivedFilesResult>;

export function SendFiles(arg1:Array<string>):Promise<void>;

export function SetAudioMode(arg1:string):Promise<void>;

export function SetAudioProfile(arg1:string):Promise<void>;

export function SetAudioTiming(arg1:string):Promise<void>;

export function SetAudioTransport(arg1:string):Promise<void>;

export function SetAutoReconnect(arg1:boolean):Promise<void>;

export function SetAutostart(arg1:boolean):Promise<void>;

export function SetCaptureDeviceID(arg1:string):Promise<void>;

export function SetEdgeSide(arg1:string):Promise<void>;

export function SetExitHotkey(arg1:number,arg2:number):Promise<void>;

export function SetMicDeviceID(arg1:string):Promise<void>;

export function SetMicMode(arg1:string):Promise<void>;

export function SetMicPlaybackDeviceID(arg1:string):Promise<void>;

export function SetMuteSource(arg1:boolean):Promise<void>;

export function SetPlaybackDeviceID(arg1:string):Promise<void>;

export function SetReturnAnchor(arg1:string,arg2:number,arg3:number):Promise<void>;

export function SetSensitivity(arg1:number):Promise<void>;

export function SetStartMinimized(arg1:boolean):Promise<void>;

export function SetTriggerZone(arg1:string,arg2:string,arg3:number,arg4:number):Promise<void>;

export function TrustPeer(arg1:string,arg2:string):Promise<void>;

export function UntrustPeer(arg1:string):Promise<void>;
