// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddPeer(arg1) {
  return window['go']['app']['App']['AddPeer'](arg1);
}

export function ClearReturnAnchor() {
  return window['go']['app']['App']['ClearReturnAnchor']();
}

export function ClearTriggerZone() {
  return window['go']['app']['App']['ClearTriggerZone']();
}

export function Connect(arg1) {
  return window['go']['app']['App']['Connect'](arg1);
}

export function DiscardReceivedFiles(arg1) {
  return window['go']['app']['App']['DiscardReceivedFiles'](arg1);
}

export function Disconnect() {
  return window['go']['app']['App']['Disconnect']();
}

export function GetAudioDevices() {
  return window['go']['app']['App']['GetAudioDevices']();
}

export function GetAudioMode() {
  return window['go']['app']['App']['GetAudioMode']();
}

export function GetAudioProfile() {
  return window['go']['app']['App']['GetAudioProfile']();
}

export function GetAudioTiming() {
  return window['go']['app']['App']['GetAudioTiming']();
}

export function GetAudioTransport() {
  return window['go']['app']['App']['GetAudioTransport']();
}

export function GetAutoReconnect() {
  return window['go']['app']['App']['GetAutoReconnect']();
}

export function GetAutostart() {
  return window['go']['app']['App']['GetAutostart']();
}

export function GetCaptureDeviceID() {
  return window['go']['app']['App']['GetCaptureDeviceID']();
}

export function GetDevice() {
  return window['go']['app']['App']['GetDevice']();
}

export function GetEdgeSide() {
  return window['go']['app']['App']['GetEdgeSide']();
}

export function GetExitHotkey() {
  return window['go']['app']['App']['GetExitHotkey']();
}

export function GetHealthStatus() {
  return window['go']['app']['App']['GetHealthStatus']();
}

export function GetLastPeer() {
  return window['go']['app']['App']['GetLastPeer']();
}

export function GetLoadMetrics() {
  return window['go']['app']['App']['GetLoadMetrics']();
}

export function GetLocalMonitors() {
  return window['go']['app']['App']['GetLocalMonitors']();
}

export function GetLogAnalysis() {
  return window['go']['app']['App']['GetLogAnalysis']();
}

export function GetMicDeviceID() {
  return window['go']['app']['App']['GetMicDeviceID']();
}

export function GetMicMode() {
  return window['go']['app']['App']['GetMicMode']();
}

export function GetMicPlaybackDeviceID() {
  return window['go']['app']['App']['GetMicPlaybackDeviceID']();
}

export function GetMuteSource() {
  return window['go']['app']['App']['GetMuteSource']();
}

export function GetPeers() {
  return window['go']['app']['App']['GetPeers']();
}

export function GetPlaybackDeviceID() {
  return window['go']['app']['App']['GetPlaybackDeviceID']();
}

export function GetRecentLogs() {
  return window['go']['app']['App']['GetRecentLogs']();
}

export function GetReturnAnchor() {
  return window['go']['app']['App']['GetReturnAnchor']();
}

export function GetSensitivity() {
  return window['go']['app']['App']['GetSensitivity']();
}

export function GetSession() {
  return window['go']['app']['App']['GetSession']();
}

export function GetStartMinimized() {
  return window['go']['app']['App']['GetStartMinimized']();
}

export function GetTailscaleStatus() {
  return window['go']['app']['App']['GetTailscaleStatus']();
}

export function GetTriggerZone() {
  return window['go']['app']['App']['GetTriggerZone']();
}

export function PickAndSendFiles() {
  return window['go']['app']['App']['PickAndSendFiles']();
}

export function Reconnect() {
  return window['go']['app']['App']['Reconnect']();
}

export function RemovePeer(arg1) {
  return window['go']['app']['App']['RemovePeer'](arg1);
}

export function SaveReceivedFiles(arg1) {
  return window['go']['app']['App']['SaveReceivedFiles'](arg1);
}

export function SendFiles(arg1) {
  return window['go']['app']['App']['SendFiles'](arg1);
}

export function SetAudioMode(arg1) {
  return window['go']['app']['App']['SetAudioMode'](arg1);
}

export function SetAudioProfile(arg1) {
  return window['go']['app']['App']['SetAudioProfile'](arg1);
}

export function SetAudioTiming(arg1) {
  return window['go']['app']['App']['SetAudioTiming'](arg1);
}

export function SetAudioTransport(arg1) {
  return window['go']['app']['App']['SetAudioTransport'](arg1);
}

export function SetAutoReconnect(arg1) {
  return window['go']['app']['App']['SetAutoReconnect'](arg1);
}

export function SetAutostart(arg1) {
  return window['go']['app']['App']['SetAutostart'](arg1);
}

export function SetCaptureDeviceID(arg1) {
  return window['go']['app']['App']['SetCaptureDeviceID'](arg1);
}

export function SetEdgeSide(arg1) {
  return window['go']['app']['App']['SetEdgeSide'](arg1);
}

export function SetExitHotkey(arg1, arg2) {
  return window['go']['app']['App']['SetExitHotkey'](arg1, arg2);
}

export function SetMicDeviceID(arg1) {
  return window['go']['app']['App']['SetMicDeviceID'](arg1);
}

export function SetMicMode(arg1) {
  return window['go']['app']['App']['SetMicMode'](arg1);
}

export function SetMicPlaybackDeviceID(arg1) {
  return window['go']['app']['App']['SetMicPlaybackDeviceID'](arg1);
}

export function SetMuteSource(arg1) {
  return window['go']['app']['App']['SetMuteSource'](arg1);
}

export function SetPlaybackDeviceID(arg1) {
  return window['go']['app']['App']['SetPlaybackDeviceID'](arg1);
}

export function SetReturnAnchor(arg1, arg2, arg3) {
  return window['go']['app']['App']['SetReturnAnchor'](arg1, arg2, arg3);
}

export function SetSensitivity(arg1) {
  return window['go']['app']['App']['SetSensitivity'](arg1);
}

export function SetStartMinimized(arg1) {
  return window['go']['app']['App']['SetStartMinimized'](arg1);
}

export function SetTriggerZone(arg1, arg2, arg3, arg4) {
  return window['go']['app']['App']['SetTriggerZone'](arg1, arg2, arg3, arg4);
}

export function TrustPeer(arg1, arg2) {
  return window['go']['app']['App']['TrustPeer'](arg1, arg2);
}

export function UntrustPeer(arg1) {
  return window['go']['app']['App']['UntrustPeer'](arg1);
}
